### PR TITLE
feat: support us-east-2 hosted zone name id

### PR DESCRIPTION
**Pull request by k-hal**
Added definition of hosted_zone_id for us-east-2, 
because ALIAS configuration for us-east-2 ALB failed on 0.5.13

### CODE REVIEW

**Comment by itkq** [comment]
How about supporting us-east-2 for other service endpoints like s3 website endpoint at the same time?

**Comment by k-hal** [comment]
Thanks for the comment.
I'll look up the zone id for S3 and CLB.

**Comment by k-hal** [comment]
I checked s3 website hosting and added hosted_zone_id.

However, us-east-2 of `DUALSTACK_CANONICAL_HOSTED_ZONE_NAME_IDS` has not been added because classic network environment cannot be prepared.

**Comment by itkq** [comment]
As long as I did some experiments in my AWS account, hosted zone ID for ALB without the `dualstack.` prefix seems to be an alias to another one now. In other words, the unique hosted zone ID on https://docs.aws.amazon.com/general/latest/gr/elb.html is available regardless of the existence of the `dualstack.` prefix.
I would recommend adding the same mapping to `DUALSTACK_CANONICAL_HOSTED_ZONE_NAME_IDS`, otherwise `dualstack.` prefixed record values cannot be set in the current implementation.

**Comment by k-hal** [comment]
Thanks for providing the link to the document. I wasn't aware of the existence of that document.

I've added mapping to `DUALSTACK_CANONICAL_HOSTED_ZONE_NAME_IDS`.

**Comment by itkq** [comment]
Released as v0.5.14.

**Pull request merged**
