### PR TITLE
'roadwork -t' fails immediately if a record of 'CAA' resource type is defined.

### PR DESCRIPTION
**Pull request by chiro**
Hi,

Route53 started to support 'CAA' records recently [[link](https://aws.amazon.com/about-aws/whats-new/2017/08/amazon-route-53-now-supports-caa-records/?nc1=h_ls)], but we cannot use roadworker's test functionality if DSL contains 'CAA' records because net-dns gem doesn't support the resource type 
 [[link](http://www.rubydoc.info/gems/net-dns/Net/DNS/QueryTypes)]. I'm trying to fix this by adding a check in dsl-tester.rb. Please take a look.

Thanks!

### CODE REVIEW

**Comment by limitusus** [comment]
I think this patch is okay for now (worked on my side).

But using [net-dns2](https://rubygems.org/gems/net-dns2) itself looks a problem, as it was last updated 2015 and the repository seems disappeared 😢 
We may need to switch to another DNS resolving gem, dnsruby used in spec for example. @winebarrel

**Comment by limitusus** [comment]
#61

**Comment by winebarrel** [comment]
I have just merged #67 
Sorry for the delay in fixing

**Comment by chiro** [comment]
I confirmed it's fixed on my local machine. 👍
Do you have any plans to make new release with the change?

**Comment by chiro** [comment]
No problem at all. Thank you for making the great tool :)

**Pull request closed without merging**
